[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "LiveTune"
version = "0.0.1"
authors = [
  { name="Aiden Tabrizi", email="taiden@ucsd.edu" },
  { name="Soheil Zibakhsh", email="szibakhshshabgahi@ucsd.edu" },
]
description = "Python package for ML developers and researchers to change certain variables while their code is executing to make the task of training a ML project easier. This package will allow you to tune some parameters while your code is live from outside of the program."
readme = "README.md"
requires-python = ">=3.7"
install_requires = []
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Repository" = "https://github.com/soheilzi/LiveTune"

[tool.flit.scripts]
updateVar = "LiveTune.updateVar:main"
